kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: efs
  annotations: null
  volume.beta.kubernetes.io/storage-class: aws-efs
spec:
  accessModes:
    - ReadWriteMany
  resources: null
  requests:
    storage: 1Mi
  selector: null
  matchLabels:
    type: nfs-kubernetes
